#!/bin/bash
# Menu module — auto-discovered by llama_manager.sh
# To add this module's entry to the main menu, ensure:
#   MENU_LABEL, MENU_FN, MENU_COLOR, and MENU_ORDER are set.
MENU_LABEL="Download Models --FAULTY--"
MENU_FN="download_menu"
MENU_COLOR="${B_CYAN}"
MENU_ORDER=20

# lib/download.sh — Background download engine and model browser
# Requires: globals.sh

# ── Find best available terminal emulator ─────────────────────────────────
find_terminal() {
    for term in x-terminal-emulator gnome-terminal xterm konsole \
                xfce4-terminal lxterminal mate-terminal; do
        command -v "$term" &>/dev/null && echo "$term" && return
    done
    echo ""
}

# ── Check if curl is available ────────────────────────────────────────────
check_curl() {
    if ! command -v curl &>/dev/null; then
        ERR "curl is not installed."
        echo "  Install with: sudo apt-get install curl"
        return 1
    fi
    return 0
}

# ── Check network connectivity ────────────────────────────────────────────
check_network() {
    if ! curl -s --max-time 5 -I https://huggingface.co &>/dev/null; then
        ERR "Cannot reach huggingface.co. Check your internet connection."
        return 1
    fi
    return 0
}

# ── Validate and fix HuggingFace URLs ─────────────────────────────────────
fix_hf_url() {
    local url="$1"
    # Fix common mistake: blob/main → resolve/main
    if [[ "$url" == *"huggingface.co"* && "$url" == *"/blob/"* ]]; then
        url="${url//\/blob\//\/resolve\/}"
        echo "$url"
        return 0
    fi
    echo "$url"
}

# ── Download status for the main menu status bar ──────────────────────────
show_download_status() {
    [[ -d "$DL_DIR" ]] || return 0
    local active=0 done_count=0 failed=0
    for f in "$DL_DIR"/*.status; do
        [[ -f "$f" ]] || continue
        local st
        st=$(cat "$f" 2>/dev/null || echo "")
        case "$st" in
            RUNNING)   (( active++ )) ;;
            DONE)      (( done_count++ )) ;;
            FAILED)    (( failed++ )) ;;
        esac
    done
    (( active > 0 ))     && echo -e "  Downloads:     ${B_YELLOW}⬇  $active in progress${NC}"
    (( done_count > 0 )) && echo -e "  Downloads:     ${B_GREEN}✔  $done_count completed (clear with option 2)${NC}"
    (( failed > 0 ))     && echo -e "  Downloads:     ${B_RED}✖  $failed failed (check logs)${NC}"
}

# ── Create standalone download script (no function export needed) ─────────
create_download_script() {
    local url="$1" filename="$2" dest="$3" state_file="$4" script_file="$5"
    
    cat > "$script_file" << 'SCRIPTEOF'
#!/bin/bash
# Standalone download script - generated by download module

B_GREEN='\033[1;32m'
B_RED='\033[1;31m'
B_YELLOW='\033[1;33m'
NC='\033[0m'

url="$1"
filename="$2"
dest="$3"
state_file="$4"

echo "RUNNING" > "$state_file"
echo ""
echo "  Downloading: $filename"
echo "  To:          $dest/$filename"
echo "  Source:      $url"
echo ""

# Try download with progress bar
if curl -L --fail --progress-bar "$url" -o "$dest/$filename.part" 2>&1; then
    mv "$dest/$filename.part" "$dest/$filename"
    echo "DONE" > "$state_file"
    echo ""
    echo -e "  ${B_GREEN}✔ Download complete: $dest/$filename${NC}"
    echo ""
    echo "  File size: $(du -h "$dest/$filename" | cut -f1)"
else
    exit_code=$?
    echo "FAILED" > "$state_file"
    rm -f "$dest/$filename.part"
    echo ""
    echo -e "  ${B_RED}✖ Download FAILED for $filename${NC}"
    echo ""
    echo "  Possible reasons:"
    case $exit_code in
        6)  echo "  - Could not resolve host (DNS issue)" ;;
        7)  echo "  - Failed to connect to host (network issue)" ;;
        22) echo "  - HTTP error (file not found or access denied)" ;;
        28) echo "  - Operation timeout" ;;
        35) echo "  - SSL/TLS connection error" ;;
        *)  echo "  - curl exit code: $exit_code" ;;
    esac
    echo "  - URL may be invalid, gated, or require authentication"
    echo "  - Network connectivity issue"
fi
echo ""
read -rp "  Press Enter to close this window..."
SCRIPTEOF
    chmod +x "$script_file"
}

# ── Spawn a download in a new terminal window ─────────────────────────────
spawn_download() {
    local url="$1" filename="$2"
    
    # Check prerequisites
    if ! check_curl; then
        read -p "Press Enter to return..."; return 1
    fi
    
    if ! check_network; then
        read -p "Press Enter to return..."; return 1
    fi
    
    mkdir -p "$MODEL_DIR" "$DL_DIR"

    if [[ -f "$MODEL_DIR/$filename" ]]; then
        echo -e "${B_YELLOW}[!] $filename already exists.${NC}"
        read -r -p "  Overwrite? (y/n): " ow
        if [[ "${ow,,}" != "y" ]]; then
            return
        fi
        mv "$MODEL_DIR/$filename" "$MODEL_DIR/$filename.bak"
    fi

    # Fix HuggingFace URL if needed
    local fixed_url
    fixed_url=$(fix_hf_url "$url")
    if [[ "$fixed_url" != "$url" ]]; then
        INFO "Fixed URL format: blob → resolve"
        url="$fixed_url"
    fi

    local safe_name="${filename//[^a-zA-Z0-9._-]/_}"
    local state_file="$DL_DIR/${safe_name}.status"
    local script_file="$DL_DIR/${safe_name}.sh"
    echo "QUEUED" > "$state_file"

    # Create standalone download script
    create_download_script "$url" "$filename" "$MODEL_DIR" "$state_file" "$script_file"

    local term
    term=$(find_terminal)

    if [[ -z "$term" ]]; then
        WARN "No terminal emulator found. Downloading in background."
        echo "  Progress will be logged to: $DL_DIR/${safe_name}.log"
        (
            bash "$script_file" "$url" "$filename" "$MODEL_DIR" "$state_file" \
                > "$DL_DIR/${safe_name}.log" 2>&1
        ) &
        local pid=$!
        OK "Download started in background (PID $pid)."
        echo "  Monitor progress: tail -f $DL_DIR/${safe_name}.log"
        sleep 3
        return
    fi

    # Spawn in terminal emulator
    case "$term" in
        gnome-terminal)
            gnome-terminal --title="Downloading $filename" -- bash -c \
                "bash '$script_file' '$url' '$filename' '$MODEL_DIR' '$state_file'" &
            ;;
        xterm)
            xterm -T "Downloading $filename" -e \
                "bash '$script_file' '$url' '$filename' '$MODEL_DIR' '$state_file'" &
            ;;
        konsole)
            konsole --title "Downloading $filename" -e \
                "bash '$script_file' '$url' '$filename' '$MODEL_DIR' '$state_file'" &
            ;;
        xfce4-terminal)
            xfce4-terminal --title="Downloading $filename" -e \
                "bash '$script_file' '$url' '$filename' '$MODEL_DIR' '$state_file'" &
            ;;
        lxterminal|mate-terminal)
            "$term" -t "Downloading $filename" -e \
                "bash '$script_file' '$url' '$filename' '$MODEL_DIR' '$state_file'" &
            ;;
        x-terminal-emulator)
            x-terminal-emulator -e \
                "bash '$script_file' '$url' '$filename' '$MODEL_DIR' '$state_file'" &
            ;;
    esac

    OK "Download window opened for $filename — you can continue using the menu."
    sleep 2
}

# ================================================================
#  MODEL BROWSER
# ================================================================
download_menu() {
    while true; do
        draw_header
        echo -e "${B_CYAN}[ 📥  MODEL DOWNLOADER ]${NC}"
        echo ""

        # Show active downloads
        if [[ -d "$DL_DIR" ]]; then
            local any_shown=0
            for f in "$DL_DIR"/*.status; do
                [[ -f "$f" ]] || continue
                local name st
                name=$(basename "$f" .status)
                st=$(cat "$f" 2>/dev/null || echo "?")
                case "$st" in
                    RUNNING) 
                        echo -e "  ${B_YELLOW}⬇ DOWNLOADING:${NC} $name"
                        # Show log tail if available
                        local logfile="$DL_DIR/${name}.log"
                        if [[ -f "$logfile" ]]; then
                            local last_line
                            last_line=$(tail -1 "$logfile" 2>/dev/null | grep -o '[0-9]*%' | tail -1)
                            [[ -n "$last_line" ]] && echo -e "     Progress: $last_line"
                        fi
                        ;;
                    DONE)    echo -e "  ${B_GREEN}✔ COMPLETE:${NC}    $name" ;;
                    FAILED)  echo -e "  ${B_RED}✖ FAILED:${NC}      $name (check $DL_DIR/${name}.log)" ;;
                    QUEUED)  echo -e "  ${B_CYAN}⏳ QUEUED:${NC}      $name" ;;
                esac
                any_shown=1
            done
            (( any_shown )) && echo ""
        fi

        echo "  Select model to download:"
        echo "  1) gemma-4-E4B-it-OBLITERATED  (Smart mid-size — Google Q5_K_M ~5.76 GB)"
        echo "  2) Mistral-7B  (Industry standard — TheBloke Q4_K_M ~4.1 GB)"
        echo "  3) Phi-3-Mini  (Tiny but powerful — bartowski Q4_K_M ~2.2 GB)"
        echo "  4) Custom URL  (Paste direct GGUF link)"
        echo "  5) Clear completed/failed status entries"
        echo "  6) View download logs"
        echo "  7) Back"
        echo ""
        local d=""
        read -r -p "  Select [1-7]: " d

        local url="" filename=""
        case $d in
            1) # FIXED: Changed blob to resolve
               url="https://huggingface.co/OBLITERATUS/gemma-4-E4B-it-OBLITERATED/resolve/main/gemma-4-E4B-it-OBLITERATED-Q5_K_M.gguf"
               filename="gemma-4-E4B-it-OBLITERATED-Q5_K_M.gguf" ;;
            2) url="https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
               filename="mistral-7b.gguf" ;;
            3) url="https://huggingface.co/bartowski/Phi-3-mini-4k-instruct-GGUF/resolve/main/Phi-3-mini-4k-instruct-Q4_K_M.gguf"
               filename="phi3-mini.gguf" ;;
            4)
               echo ""
               echo "  Enter HuggingFace URL (blob or resolve URLs both work):"
               read -r -p "  URL: " url
               echo ""
               read -r -p "  Save as filename (.gguf): " filename
               if [[ -z "$url" || -z "$filename" ]]; then
                   echo -e "${B_RED}Invalid input.${NC}"; sleep 2; continue
               fi
               [[ "$filename" != *.gguf ]] && filename="${filename}.gguf"
               
               # Validate URL format
               if [[ ! "$url" =~ ^https?:// ]]; then
                   ERR "Invalid URL format. Must start with http:// or https://"
                   sleep 2; continue
               fi
               ;;
            5)
               if [[ -d "$DL_DIR" ]]; then
                   local cleared=0
                   for f in "$DL_DIR"/*.status; do
                       [[ -f "$f" ]] || continue
                       local st; st=$(cat "$f" 2>/dev/null || echo "")
                       if [[ "$st" == "DONE" || "$st" == "FAILED" ]]; then
                           local basename="${f%.status}"
                           rm -f "$f" "${basename}.sh" "${basename}.log"
                           ((cleared++))
                       fi
                   done
                   if ((cleared > 0)); then
                       OK "Cleared $cleared completed/failed entries."
                   else
                       INFO "No completed/failed entries to clear."
                   fi
               else
                   INFO "No download directory found."
               fi
               sleep 2; continue
               ;;
            6)
               # View logs
               draw_header
               echo -e "${B_CYAN}[ 📋  Download Logs ]${NC}"
               echo ""
               if [[ ! -d "$DL_DIR" ]]; then
                   INFO "No download logs available."
               else
                   local found=0
                   for logfile in "$DL_DIR"/*.log; do
                       [[ -f "$logfile" ]] || continue
                       found=1
                       local name
                       name=$(basename "$logfile" .log)
                       echo -e "${B_YELLOW}=== $name ===${NC}"
                       tail -20 "$logfile" 2>/dev/null || echo "  (empty or unreadable)"
                       echo ""
                   done
                   if ((found == 0)); then
                       INFO "No log files found in $DL_DIR"
                   fi
               fi
               read -p "Press Enter to return..."
               continue
               ;;
            7) return ;;
            *) echo -e "${B_RED}Invalid option.${NC}"; sleep 1; continue ;;
        esac

        spawn_download "$url" "$filename"
    done
}
